from copy import deepcopy
n = [7, 2, 5]
n.append(4)
n.insert(1, 10)
n.extend([1,1,1])
n.remove(7)
j = n.pop(-1)
print(n, j)
n1 = sorted(n)
print(n1)
n1.reverse()
print(n1)
c = n1.count(2)
print(c)
print(n1.index(1))
m = n1.copy()
print(m)
v = deepcopy(n1)
print(v)
n1.clear()
print(n1, m, v)